In [1]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
covertype = fetch_ucirepo(id=31) 
  
# data (as pandas dataframes) 
X = covertype.data.features 
y = covertype.data.targets 
  
# metadata 
print(covertype.metadata) 
  
# variable information 
print(covertype.variables)

{'uci_id': 31, 'name': 'Covertype', 'repository_url': 'https://archive.ics.uci.edu/dataset/31/covertype', 'data_url': 'https://archive.ics.uci.edu/static/public/31/data.csv', 'abstract': 'Classification of pixels into 7 forest cover types based on attributes such as elevation, aspect, slope, hillshade, soil-type, and more.', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 581012, 'num_features': 54, 'feature_types': ['Categorical', 'Integer'], 'demographics': [], 'target_col': ['Cover_Type'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1998, 'last_updated': 'Sat Mar 16 2024', 'dataset_doi': '10.24432/C50K5N', 'creators': ['Jock Blackard'], 'intro_paper': None, 'additional_info': {'summary': 'Predicting forest cover type from cartographic variables only (no remotely sensed data).  The actual forest cover type for a given observation (30 x 30 meter cell) was determined from US Forest Service (USFS) Region 2 Resource Information System (RIS) data.  Independent variables were derived from data originally obtained from US Geological Survey (USGS) and USFS data.  Data is in raw form (not scaled) and contains binary (0 or 1) columns of data for qualitative independent variables (wilderness areas and soil types).\r\n\r\nThis study area includes four wilderness areas located in the Roosevelt National Forest of northern Colorado.  These areas represent forests with minimal human-caused disturbances, so that existing forest cover types are more a result of ecological processes rather than forest management practices.\r\n\r\nSome background information for these four wilderness areas: Neota (area 2) probably has the highest mean elevational value of the 4 wilderness areas. Rawah (area 1) and Comanche Peak (area 3) would have a lower mean elevational value, while Cache la Poudre (area 4) would have the lowest mean elevational value. \r\n\r\nAs for primary major tree species in these areas, Neota would have spruce/fir (type 1), while Rawah and Comanche Peak would probably have lodgepole pine (type 2) as their primary species, followed by spruce/fir and aspen (type 5). Cache la Poudre would tend to have Ponderosa pine (type 3), Douglas-fir (type 6), and cottonwood/willow (type 4).  \r\n\r\nThe Rawah and Comanche Peak areas would tend to be more typical of the overall dataset than either the Neota or Cache la Poudre, due to their assortment of tree species and range of predictive variable values (elevation, etc.)  Cache la Poudre would probably  be more unique than the others, due to its relatively low  elevation range and species composition. ', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Given is the attribute name, attribute type, the measurement unit and a brief description.  The forest cover type is the classification  problem.  The order of this listing corresponds to the order of numerals along the rows of the database.\r\n\r\nName / Data Type / Measurement / Description\r\n\r\nElevation / quantitative /meters / Elevation in meters\r\nAspect / quantitative / azimuth / Aspect in degrees azimuth\r\nSlope / quantitative / degrees / Slope in degrees\r\nHorizontal_Distance_To_Hydrology / quantitative / meters / Horz Dist to nearest surface water features\r\nVertical_Distance_To_Hydrology / quantitative / meters / Vert Dist to nearest surface water features\r\nHorizontal_Distance_To_Roadways / quantitative / meters / Horz Dist to nearest roadway\r\nHillshade_9am / quantitative / 0 to 255 index / Hillshade index at 9am, summer solstice\r\nHillshade_Noon / quantitative / 0 to 255 index / Hillshade index at noon, summer soltice\r\nHillshade_3pm / quantitative / 0 to 255 index / Hillshade index at 3pm, summer solstice\r\nHorizontal_Distance_To_Fire_Points / quantitative / meters / Horz Dist to nearest wildfire ignition points\r\nWilderness_Area (4 binary columns) / qualitative / 0 (absence) or 1 (presence) / Wilderness area designation\r\nSoil_Type (40 binary columns) / qualitative / 0 (absence) or 1 (presence) / Soil Type designation\r\nCover_Type (7 types) / integer / 1 to 7 / Forest Cover Type designation', 'citation': None}}
                                  name     role     type demographic  \
0                            Elevation  Feature  Integer        None
1                               Aspect  Feature  Integer        None
2                                Slope  Feature  Integer        None
3     Horizontal_Distance_To_Hydrology  Feature  Integer        None
4       Vertical_Distance_To_Hydrology  Feature  Integer        None
5      Horizontal_Distance_To_Roadways  Feature  Integer        None
6                        Hillshade_9am  Feature  Integer        None
7                       Hillshade_Noon  Feature  Integer        None
8                        Hillshade_3pm  Feature  Integer        None
9   Horizontal_Distance_To_Fire_Points  Feature  Integer        None
10                    Wilderness_Area1  Feature  Integer        None
11                          Soil_Type1  Feature  Integer        None
12                          Soil_Type2  Feature  Integer        None
13                          Soil_Type3  Feature  Integer        None
14                          Soil_Type4  Feature  Integer        None
15                          Soil_Type5  Feature  Integer        None
16                          Soil_Type6  Feature  Integer        None
17                          Soil_Type7  Feature  Integer        None
18                          Soil_Type8  Feature  Integer        None
19                          Soil_Type9  Feature  Integer        None
20                         Soil_Type10  Feature  Integer        None
21                         Soil_Type11  Feature  Integer        None
22                         Soil_Type12  Feature  Integer        None
23                         Soil_Type13  Feature  Integer        None
24                         Soil_Type14  Feature  Integer        None
25                         Soil_Type15  Feature  Integer        None
26                         Soil_Type16  Feature  Integer        None
27                         Soil_Type17  Feature  Integer        None
28                         Soil_Type18  Feature  Integer        None
29                         Soil_Type19  Feature  Integer        None
30                         Soil_Type20  Feature  Integer        None
31                         Soil_Type21  Feature  Integer        None
32                         Soil_Type22  Feature  Integer        None
33                         Soil_Type23  Feature  Integer        None
34                         Soil_Type24  Feature  Integer        None
35                         Soil_Type25  Feature  Integer        None
36                         Soil_Type26  Feature  Integer        None
37                         Soil_Type27  Feature  Integer        None
38                         Soil_Type28  Feature  Integer        None
39                         Soil_Type29  Feature  Integer        None
40                         Soil_Type30  Feature  Integer        None
41                         Soil_Type31  Feature  Integer        None
42                         Soil_Type32  Feature  Integer        None
43                         Soil_Type33  Feature  Integer        None
44                         Soil_Type34  Feature  Integer        None
45                         Soil_Type35  Feature  Integer        None
46                         Soil_Type36  Feature  Integer        None
47                         Soil_Type37  Feature  Integer        None
48                         Soil_Type38  Feature  Integer        None
49                         Soil_Type39  Feature  Integer        None
50                         Soil_Type40  Feature  Integer        None
51                          Cover_Type   Target  Integer        None
52                    Wilderness_Area2  Feature  Integer        None
53                    Wilderness_Area3  Feature  Integer        None
54                    Wilderness_Area4  Feature  Integer        None

   description units missing_values
0         None  None             no
1         None  None             no
2         None  None             no
3         None  None             no
4         None  None             no
5         None  None             no
6         None  None             no
7         None  None             no
8         None  None             no
9         None  None             no
10        None  None             no
11        None  None             no
12        None  None             no
13        None  None             no
14        None  None             no
15        None  None             no
16        None  None             no
17        None  None             no
18        None  None             no
19        None  None             no
20        None  None             no
21        None  None             no
22        None  None             no
23        None  None             no
24        None  None             no
25        None  None             no
26        None  None             no
27        None  None             no
28        None  None             no
29        None  None             no
30        None  None             no
31        None  None             no
32        None  None             no
33        None  None             no
34        None  None             no
35        None  None             no
36        None  None             no
37        None  None             no
38        None  None             no
39        None  None             no
40        None  None             no
41        None  None             no
42        None  None             no
43        None  None             no
44        None  None             no
45        None  None             no
46        None  None             no
47        None  None             no
48        None  None             no
49        None  None             no
50        None  None             no
51        None  None             no
52        None  None             no
53        None  None             no
54        None  None             no

In [2]:
X

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,0
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,0
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,0
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,0
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,...,0,0,0,0,0,0,0,0,1,0
581008,2391,152,19,67,12,95,240,237,119,845,...,0,0,0,0,0,0,0,0,1,0
581009,2386,159,17,60,7,90,236,241,130,854,...,0,0,0,0,0,0,0,0,1,0
581010,2384,170,15,60,5,90,230,245,143,864,...,0,0,0,0,0,0,0,0,1,0
581011,2383,165,13,60,4,67,231,244,141,875,...,0,0,0,0,0,0,0,0,1,0

In [3]:
X.isnull().sum()

Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0
Soil_Type11                           0
Soil_Type12                           0
Soil_Type13                           0
Soil_Type14                           0
Soil_Type15                           0
Soil_Type16                           0
Soil_Type17                           0
Soil_Type18                           0
Soil_Type19                           0
Soil_Type20                           0
Soil_Type21                           0
Soil_Type22                           0
Soil_Type23                           0
Soil_Type24                           0
Soil_Type25                           0
Soil_Type26                           0
Soil_Type27                           0
Soil_Type28                           0
Soil_Type29                           0
Soil_Type30                           0
Soil_Type31                           0
Soil_Type32                           0
Soil_Type33                           0
Soil_Type34                           0
Soil_Type35                           0
Soil_Type36                           0
Soil_Type37                           0
Soil_Type38                           0
Soil_Type39                           0
Soil_Type40                           0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
dtype: int64

In [4]:
y

        Cover_Type
0                5
1                5
2                2
3                2
4                5
...            ...
581007           3
581008           3
581009           3
581010           3
581011           3

[581012 rows x 1 columns]

# Data Normalization

In [5]:
from sklearn.preprocessing import StandardScaler
st_scale = StandardScaler()
scaled_x = st_scale.fit_transform(X)

In [6]:
scaled_x

array([[-1.29780509, -0.93515698, -1.48281978, ..., -0.23285905,
        -0.87936402, -0.26067295],
       [-1.31923485, -0.89047967, -1.61636259, ..., -0.23285905,
        -0.87936402, -0.26067295],
       [-0.5549068 , -0.14883628, -0.68156292, ..., -0.23285905,
        -0.87936402, -0.26067295],
       ...,
       [-2.04784663,  0.02987297,  0.38677957, ..., -0.23285905,
         1.13718548, -0.26067295],
       [-2.05498988,  0.12816306,  0.11969395, ..., -0.23285905,
         1.13718548, -0.26067295],
       [-2.05856151,  0.08348575, -0.14739167, ..., -0.23285905,
         1.13718548, -0.26067295]], shape=(581012, 54))

# Min Max Scaler

In [7]:
from sklearn.preprocessing import MinMaxScaler
min_max_scale = MinMaxScaler()
Min_Max_X = min_max_scale.fit_transform(X)

In [9]:
Min_Max_X[0]

array([0.36868434, 0.14166667, 0.04545455, 0.18468146, 0.22351421,
       0.07165941, 0.87007874, 0.91338583, 0.58267717, 0.87536596,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(scaled_x,y)

In [11]:
from sklearn.svm import SVC
svm_poly = SVC(kernel='poly')
svm_rbf = SVC(kernel='rbf')

In [ ]:
svm_poly.fit(X_train,y_train)

C:\Users\GrowTech\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
svm_rbf.fit(X_train,y_train)